# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/api/v2/core/base.proto

require 'google/protobuf'

require 'envoy/api/v2/core/http_uri_pb'
require 'google/protobuf/any_pb'
require 'google/protobuf/struct_pb'
require 'google/protobuf/wrappers_pb'
require 'envoy/type/percent_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/api/v2/core/base.proto", :syntax => :proto3) do
    add_message "envoy.api.v2.core.Locality" do
      optional :region, :string, 1
      optional :zone, :string, 2
      optional :sub_zone, :string, 3
    end
    add_message "envoy.api.v2.core.Node" do
      optional :id, :string, 1
      optional :cluster, :string, 2
      optional :metadata, :message, 3, "google.protobuf.Struct"
      optional :locality, :message, 4, "envoy.api.v2.core.Locality"
      optional :build_version, :string, 5
    end
    add_message "envoy.api.v2.core.Metadata" do
      map :filter_metadata, :string, :message, 1, "google.protobuf.Struct"
    end
    add_message "envoy.api.v2.core.RuntimeUInt32" do
      optional :default_value, :uint32, 2
      optional :runtime_key, :string, 3
    end
    add_message "envoy.api.v2.core.HeaderValue" do
      optional :key, :string, 1
      optional :value, :string, 2
    end
    add_message "envoy.api.v2.core.HeaderValueOption" do
      optional :header, :message, 1, "envoy.api.v2.core.HeaderValue"
      optional :append, :message, 2, "google.protobuf.BoolValue"
    end
    add_message "envoy.api.v2.core.HeaderMap" do
      repeated :headers, :message, 1, "envoy.api.v2.core.HeaderValue"
    end
    add_message "envoy.api.v2.core.DataSource" do
      oneof :specifier do
        optional :filename, :string, 1
        optional :inline_bytes, :bytes, 2
        optional :inline_string, :string, 3
      end
    end
    add_message "envoy.api.v2.core.RemoteDataSource" do
      optional :http_uri, :message, 1, "envoy.api.v2.core.HttpUri"
      optional :sha256, :string, 2
    end
    add_message "envoy.api.v2.core.AsyncDataSource" do
      oneof :specifier do
        optional :local, :message, 1, "envoy.api.v2.core.DataSource"
        optional :remote, :message, 2, "envoy.api.v2.core.RemoteDataSource"
      end
    end
    add_message "envoy.api.v2.core.TransportSocket" do
      optional :name, :string, 1
      oneof :config_type do
        optional :config, :message, 2, "google.protobuf.Struct"
        optional :typed_config, :message, 3, "google.protobuf.Any"
      end
    end
    add_message "envoy.api.v2.core.SocketOption" do
      optional :description, :string, 1
      optional :level, :int64, 2
      optional :name, :int64, 3
      optional :state, :enum, 6, "envoy.api.v2.core.SocketOption.SocketState"
      oneof :value do
        optional :int_value, :int64, 4
        optional :buf_value, :bytes, 5
      end
    end
    add_enum "envoy.api.v2.core.SocketOption.SocketState" do
      value :STATE_PREBIND, 0
      value :STATE_BOUND, 1
      value :STATE_LISTENING, 2
    end
    add_message "envoy.api.v2.core.RuntimeFractionalPercent" do
      optional :default_value, :message, 1, "envoy.type.FractionalPercent"
      optional :runtime_key, :string, 2
    end
    add_message "envoy.api.v2.core.ControlPlane" do
      optional :identifier, :string, 1
    end
    add_enum "envoy.api.v2.core.RoutingPriority" do
      value :DEFAULT, 0
      value :HIGH, 1
    end
    add_enum "envoy.api.v2.core.RequestMethod" do
      value :METHOD_UNSPECIFIED, 0
      value :GET, 1
      value :HEAD, 2
      value :POST, 3
      value :PUT, 4
      value :DELETE, 5
      value :CONNECT, 6
      value :OPTIONS, 7
      value :TRACE, 8
      value :PATCH, 9
    end
    add_enum "envoy.api.v2.core.TrafficDirection" do
      value :UNSPECIFIED, 0
      value :INBOUND, 1
      value :OUTBOUND, 2
    end
  end
end

module Envoy
  module Api
    module V2
      module Core
        Locality = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.Locality").msgclass
        Node = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.Node").msgclass
        Metadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.Metadata").msgclass
        RuntimeUInt32 = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RuntimeUInt32").msgclass
        HeaderValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.HeaderValue").msgclass
        HeaderValueOption = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.HeaderValueOption").msgclass
        HeaderMap = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.HeaderMap").msgclass
        DataSource = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.DataSource").msgclass
        RemoteDataSource = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RemoteDataSource").msgclass
        AsyncDataSource = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.AsyncDataSource").msgclass
        TransportSocket = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.TransportSocket").msgclass
        SocketOption = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.SocketOption").msgclass
        SocketOption::SocketState = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.SocketOption.SocketState").enummodule
        RuntimeFractionalPercent = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RuntimeFractionalPercent").msgclass
        ControlPlane = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.ControlPlane").msgclass
        RoutingPriority = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RoutingPriority").enummodule
        RequestMethod = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.RequestMethod").enummodule
        TrafficDirection = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.api.v2.core.TrafficDirection").enummodule
      end
    end
  end
end
