# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/data/accesslog/v2/accesslog.proto

require 'google/protobuf'

require 'envoy/api/v2/core/address_pb'
require 'envoy/api/v2/core/base_pb'
require 'google/protobuf/duration_pb'
require 'google/protobuf/timestamp_pb'
require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("envoy/data/accesslog/v2/accesslog.proto", :syntax => :proto3) do
    add_message "envoy.data.accesslog.v2.TCPAccessLogEntry" do
      optional :common_properties, :message, 1, "envoy.data.accesslog.v2.AccessLogCommon"
    end
    add_message "envoy.data.accesslog.v2.HTTPAccessLogEntry" do
      optional :common_properties, :message, 1, "envoy.data.accesslog.v2.AccessLogCommon"
      optional :protocol_version, :enum, 2, "envoy.data.accesslog.v2.HTTPAccessLogEntry.HTTPVersion"
      optional :request, :message, 3, "envoy.data.accesslog.v2.HTTPRequestProperties"
      optional :response, :message, 4, "envoy.data.accesslog.v2.HTTPResponseProperties"
    end
    add_enum "envoy.data.accesslog.v2.HTTPAccessLogEntry.HTTPVersion" do
      value :PROTOCOL_UNSPECIFIED, 0
      value :HTTP10, 1
      value :HTTP11, 2
      value :HTTP2, 3
    end
    add_message "envoy.data.accesslog.v2.AccessLogCommon" do
      optional :sample_rate, :double, 1
      optional :downstream_remote_address, :message, 2, "envoy.api.v2.core.Address"
      optional :downstream_local_address, :message, 3, "envoy.api.v2.core.Address"
      optional :tls_properties, :message, 4, "envoy.data.accesslog.v2.TLSProperties"
      optional :start_time, :message, 5, "google.protobuf.Timestamp"
      optional :time_to_last_rx_byte, :message, 6, "google.protobuf.Duration"
      optional :time_to_first_upstream_tx_byte, :message, 7, "google.protobuf.Duration"
      optional :time_to_last_upstream_tx_byte, :message, 8, "google.protobuf.Duration"
      optional :time_to_first_upstream_rx_byte, :message, 9, "google.protobuf.Duration"
      optional :time_to_last_upstream_rx_byte, :message, 10, "google.protobuf.Duration"
      optional :time_to_first_downstream_tx_byte, :message, 11, "google.protobuf.Duration"
      optional :time_to_last_downstream_tx_byte, :message, 12, "google.protobuf.Duration"
      optional :upstream_remote_address, :message, 13, "envoy.api.v2.core.Address"
      optional :upstream_local_address, :message, 14, "envoy.api.v2.core.Address"
      optional :upstream_cluster, :string, 15
      optional :response_flags, :message, 16, "envoy.data.accesslog.v2.ResponseFlags"
      optional :metadata, :message, 17, "envoy.api.v2.core.Metadata"
      optional :upstream_transport_failure_reason, :string, 18
      optional :route_name, :string, 19
    end
    add_message "envoy.data.accesslog.v2.ResponseFlags" do
      optional :failed_local_healthcheck, :bool, 1
      optional :no_healthy_upstream, :bool, 2
      optional :upstream_request_timeout, :bool, 3
      optional :local_reset, :bool, 4
      optional :upstream_remote_reset, :bool, 5
      optional :upstream_connection_failure, :bool, 6
      optional :upstream_connection_termination, :bool, 7
      optional :upstream_overflow, :bool, 8
      optional :no_route_found, :bool, 9
      optional :delay_injected, :bool, 10
      optional :fault_injected, :bool, 11
      optional :rate_limited, :bool, 12
      optional :unauthorized_details, :message, 13, "envoy.data.accesslog.v2.ResponseFlags.Unauthorized"
      optional :rate_limit_service_error, :bool, 14
      optional :downstream_connection_termination, :bool, 15
      optional :upstream_retry_limit_exceeded, :bool, 16
      optional :stream_idle_timeout, :bool, 17
      optional :invalid_envoy_request_headers, :bool, 18
    end
    add_message "envoy.data.accesslog.v2.ResponseFlags.Unauthorized" do
      optional :reason, :enum, 1, "envoy.data.accesslog.v2.ResponseFlags.Unauthorized.Reason"
    end
    add_enum "envoy.data.accesslog.v2.ResponseFlags.Unauthorized.Reason" do
      value :REASON_UNSPECIFIED, 0
      value :EXTERNAL_SERVICE, 1
    end
    add_message "envoy.data.accesslog.v2.TLSProperties" do
      optional :tls_version, :enum, 1, "envoy.data.accesslog.v2.TLSProperties.TLSVersion"
      optional :tls_cipher_suite, :message, 2, "google.protobuf.UInt32Value"
      optional :tls_sni_hostname, :string, 3
      optional :local_certificate_properties, :message, 4, "envoy.data.accesslog.v2.TLSProperties.CertificateProperties"
      optional :peer_certificate_properties, :message, 5, "envoy.data.accesslog.v2.TLSProperties.CertificateProperties"
      optional :tls_session_id, :string, 6
    end
    add_message "envoy.data.accesslog.v2.TLSProperties.CertificateProperties" do
      repeated :subject_alt_name, :message, 1, "envoy.data.accesslog.v2.TLSProperties.CertificateProperties.SubjectAltName"
      optional :subject, :string, 2
    end
    add_message "envoy.data.accesslog.v2.TLSProperties.CertificateProperties.SubjectAltName" do
      oneof :san do
        optional :uri, :string, 1
        optional :dns, :string, 2
      end
    end
    add_enum "envoy.data.accesslog.v2.TLSProperties.TLSVersion" do
      value :VERSION_UNSPECIFIED, 0
      value :TLSv1, 1
      value :TLSv1_1, 2
      value :TLSv1_2, 3
      value :TLSv1_3, 4
    end
    add_message "envoy.data.accesslog.v2.HTTPRequestProperties" do
      optional :request_method, :enum, 1, "envoy.api.v2.core.RequestMethod"
      optional :scheme, :string, 2
      optional :authority, :string, 3
      optional :port, :message, 4, "google.protobuf.UInt32Value"
      optional :path, :string, 5
      optional :user_agent, :string, 6
      optional :referer, :string, 7
      optional :forwarded_for, :string, 8
      optional :request_id, :string, 9
      optional :original_path, :string, 10
      optional :request_headers_bytes, :uint64, 11
      optional :request_body_bytes, :uint64, 12
      map :request_headers, :string, :string, 13
    end
    add_message "envoy.data.accesslog.v2.HTTPResponseProperties" do
      optional :response_code, :message, 1, "google.protobuf.UInt32Value"
      optional :response_headers_bytes, :uint64, 2
      optional :response_body_bytes, :uint64, 3
      map :response_headers, :string, :string, 4
      map :response_trailers, :string, :string, 5
      optional :response_code_details, :string, 6
    end
  end
end

module Envoy
  module Data
    module Accesslog
      module V2
        TCPAccessLogEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.TCPAccessLogEntry").msgclass
        HTTPAccessLogEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.HTTPAccessLogEntry").msgclass
        HTTPAccessLogEntry::HTTPVersion = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.HTTPAccessLogEntry.HTTPVersion").enummodule
        AccessLogCommon = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.AccessLogCommon").msgclass
        ResponseFlags = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.ResponseFlags").msgclass
        ResponseFlags::Unauthorized = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.ResponseFlags.Unauthorized").msgclass
        ResponseFlags::Unauthorized::Reason = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.ResponseFlags.Unauthorized.Reason").enummodule
        TLSProperties = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.TLSProperties").msgclass
        TLSProperties::CertificateProperties = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.TLSProperties.CertificateProperties").msgclass
        TLSProperties::CertificateProperties::SubjectAltName = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.TLSProperties.CertificateProperties.SubjectAltName").msgclass
        TLSProperties::TLSVersion = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.TLSProperties.TLSVersion").enummodule
        HTTPRequestProperties = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.HTTPRequestProperties").msgclass
        HTTPResponseProperties = Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.data.accesslog.v2.HTTPResponseProperties").msgclass
      end
    end
  end
end
